services:
  'build':
    container_name: 'bundler'
    build:
      context: './reproducible-builds/'
      dockerfile: './Dockerfile'
      target: 'build'
    volumes:
      - type: 'bind'
        source: './'
        target: '/project/'
  'package':
    container_name: 'packager'
    # depends_on:
    #   'build':
    #     condition: 'service_completed_successfully'
    build:
      context: './reproducible-builds/'
      dockerfile: './Dockerfile'
      target: 'package'
    volumes:
      - type: 'bind'
        source: './app/build/outputs/'
        target: '/project/'
  'sign':
    build:
      context: './reproducible-builds/'
      dockerfile: './Dockerfile'
      target: 'sign'
    stdin_open: true
    tty: true
    volumes:
      - type: 'bind'
        source: './app/build/outputs/apks/splits/'
        target: '/project/'
    secrets:
      - source: 'keystore'
        target: '/run/secrets/dev.keystore'
  'run':
    container_name: 'emulator'
    build:
      context: './reproducible-builds/'
      dockerfile: './Dockerfile'
      target: 'emulate'
    gpus: 'all'
    devices:
      - source: '/dev/kvm' # Even works with WSL2 (not WSL1)
        target: '/dev/kvm'
        permissions: 'rw'
    ports:
      - ':8080'
    volumes:
      - type: 'bind'
        source: './app/build/outputs/apks/splits/'
        target: '/project/'
secrets:
  'keystore':
    file: './dev.keystore'
