services:
  'build':
    container_name: 'bundler'
    build:
      context: './reproducible-builds/'
      dockerfile: './Dockerfile'
      target: 'build'
    volumes:
      - type: 'bind'
        source: './'
        target: '/project/'
  'package':
    container_name: 'packager'
    # depends_on:
    #   'build':
    #     condition: 'service_completed_successfully'
    build:
      context: './reproducible-builds/'
      dockerfile: './Dockerfile'
      target: 'package'
    volumes:
      - type: 'bind'
        source: './app/build/outputs/'
        target: '/project/'
  'run':
    container_name: 'emulator'
    # depends_on:
    #   'package':
    #     condition: 'service_completed_successfully'
    build:
      context: './reproducible-builds/'
      dockerfile: './Dockerfile'
      target: 'emulate'
    ports:
      - ':8080'
      - ':8081'
    volumes:
      - type: 'bind'
        source: './app/build/outputs/apks/splits/'
        target: '/project/'
