services:
  'ws-scrcpy-with-adb':
    extends:
      file: './reproducible-builds/ws-scrcpy/docker-compose.yml'
      service: 'ws-scrcpy'
    build:
      additional_contexts:
        'new_base': 'service:build'
      args:
        - 'BASE_IMAGE=new_base'
  'build':
    container_name: 'bundler'
    build:
      context: './reproducible-builds/'
      dockerfile: './Dockerfile'
      target: 'build'
    volumes:
      - type: 'bind'
        source: './'
        target: '/project/'
  'package':
    container_name: 'packager'
    build:
      context: './reproducible-builds/'
      dockerfile: './Dockerfile'
      target: 'package'
    volumes:
      - type: 'bind'
        source: './app/build/outputs/'
        target: '/project/'
  'sign':
    build:
      context: './reproducible-builds/'
      dockerfile: './Dockerfile'
      target: 'sign'
    stdin_open: true
    tty: true
    volumes:
      - type: 'bind'
        # source: './app/build/outputs/apks/splits/'
        source: './app/build/outputs/apk/websiteProd/release/'
        target: '/project/'
    secrets:
      - source: 'all'
        target: '/run/secrets/'
  'run':
    container_name: 'emulator'
    build:
      context: './reproducible-builds/'
      dockerfile: './Dockerfile'
      target: 'emulate'
      additional_contexts:
        'ws_scrcpy': 'service:ws-scrcpy-with-adb'
      # args:
      #   - APKS="Signal-Android-website-prod-arm64-v8a-release-unsigned-7.52.2.apk"
    gpus: 'all'
    devices:
      - source: '/dev/kvm' # Even works with WSL2 (not WSL1)
        target: '/dev/kvm'
        permissions: 'rw'
    ports:
      - ':8000'
    volumes:
      - type: 'bind'
        # source: './app/build/outputs/apks/splits/'
        source: './app/build/outputs/apk/websiteProd/release/'
        target: '/project'
secrets:
  'all':
    file: './reproducible-builds/secrets/'
